// Placeholder — the counter smoke test generated by `flutter create` referenced
// the old package name (app1) and a MyApp class that no longer exists.
// Real integration tests live in the flutter_gemma package's example/.
void main() {}
